/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id ("java")
    id ("com.github.johnrengelman.shadow") version "7.0.0"
} 

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.1")
    implementation ("com.fasterxml.jackson.core:jackson-databind:2.12.3")
    implementation ("com.fasterxml.jackson.core:jackson-core:2.12.3")
    implementation ("com.fasterxml.jackson.core:jackson-annotations:2.12.3")
}

tasks.jar {
    // Customize the JAR file name
    archiveFileName.set("TargetGame.jar")

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    archiveFileName.set("$buildDir/libs/TargetGame.jar")

    // Add the Resources folder to the build
    from("src/main/Resources")

    // Set manifest attributes
    manifest {
        attributes["Main-Class"] = "com.example.AppMain"
    }
}

tasks.shadowJar {
    mergeServiceFiles()
    archiveClassifier.set("")
}
